name: Tests
on:
  push:
    branches: [main]
  # Triggers the workflow on pull request events.
  pull_request:
    types: [opened, reopened, synchronize]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs.
concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test_results:
    name: Verify Stable Test Results
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Check stable test results
        run: |
          [[ "${{ needs.tests.outputs.stable_failed }}" != "1" ]]
  tests:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{matrix.gemfile}}
    strategy:
      matrix:
        ruby:
          - "3.4"
          - "3.3"
          - "3.2"
          - "jruby-9.4.14.0"
        gemfile:
          - gemfiles/ar81.gemfile
        channel: ["stable"]
        exclude:
          - ruby: "jruby-9.4.14.0"
            gemfile: gemfiles/ar81.gemfile
            channel: "stable"
        include:
          - ruby: head
            gemfile: gemfiles/ar81.gemfile
            channel: "experimental"
          - ruby: jruby-head
            gemfile: gemfiles/ar81.gemfile
            channel: "experimental"
    continue-on-error: ${{ matrix.channel != 'stable' }}
    outputs:
      stable_failed: ${{ steps.mark_failure.outputs.failure }}
    steps:
      - name: Set Up Gems
        uses: actions/checkout@v4
      - name: Set Up Deps
        run: sudo apt-get install libgeos-dev
      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Test
        run: bundle exec rake
      - name: Mark failure
        id: mark_failure
        if: ${{ failure() && matrix.channel == 'stable' }}
        run: echo "failure=1" >> $GITHUB_OUTPUT
